[package]
name = "danish-rust"
version = "0.1.0"
authors = ["Andrew McConachie <andrew@depht.com>"]
edition = "2018"

[dependencies]
pcap = { version = "0.7", features = ["tokio"] }
ctrlc = { version = "3.0", features = ["termination"] }
